# Generated by Django 3.2.5 on 2022-11-09 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, max_length=300, unique=True, verbose_name='Ссылка, НЕ ЗАПОЛНЯТЬ')),
                ('body', models.TextField(blank=True, db_index=True, verbose_name='Текст комментария')),
                ('date_pub', models.DateTimeField(auto_now_add=True, verbose_name='Время публикации')),
            ],
            options={
                'verbose_name': 'Комментарий',
                'verbose_name_plural': 'Комментарии',
            },
        ),
    ]
